Fix warnings and add checks as much as possible.

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -12,7 +12,7 @@ function print_usage() {
 	echo "Usage: $0 [options]"
 	echo "Options:"
 	echo "  --help|-h: print this help"
-	echo "  --all|-a: install all packages"
+	echo "  --all|-a: install all softwares"
 	echo "  --molcas: install Molcas"
 	echo "  --utchem: install UTChem"
 	echo "  --dirac: install Dirac"
@@ -220,7 +220,7 @@ function test_utchem() {
 				echo "End running test script"
 
 				#<< "#COMMENT"
-				tests_count=$(($tests_count + 1))
+				tests_count=$((tests_count + 1))
 				# a.utout.nproc=1 a.utout.nproc=2 a.utout.nproc=4 => a.utout.nproc=4
 				reference_output=$(ls "$TEST_SCRIPT_DIR/$OUTPUT" | tail -n 1)
 				result_output="$TEST_SCRIPT_DIR/${TEST_RESULTS}/$OUTPUT"
@@ -336,7 +336,7 @@ function setup_utchem() {
 	#   (e.g. If you installed a python executable file at /home/users/username/python)
 	#   ./configure --python=/home/users/username/python
 	cd "${UTCHEM_BUILD_DIR}"
-	UTCHEM_MPI="$(dirname "$(which mpif77 | xargs dirname)")"
+	UTCHEM_MPI="$(dirname "$(which mpiifort | xargs dirname)")"
 	./configure --mpi="$UTCHEM_MPI" --python=python2 2>&1 | tee "$SCRIPT_PATH/utchem-make.log"
 
 	# Make utchem (${UTCHEM_BUILD_DIR}/boot/utchem is executable file)
@@ -400,12 +400,12 @@ function set_ompi_path() {
 
 function setup_dirac() {
 	cd "$SCRIPT_PATH"
-	pyenv global "$PYTHON3_VERSION"
 	DIRAC_SCR="$HOME/dirac_scr"
 	mkdir -p "$DIRAC_SCR"
-	DIRAC_NPROCS=$(($SETUP_NPROCS / $dirac_counts))
-	OMPI_VERSION="$OPENMPI4_VERSION" # DIRAC 19.0 and 21.1 use this version of OpenMPI
-	set_ompi_path                    # set OpenMPI PATH
+	# Set DIRAC_NPROCS (if SETUP_NPROCS is less than dirac_counts, set 1)
+	DIRAC_NPROCS=$((SETUP_NPROCS > dirac_counts ? SETUP_NPROCS / dirac_counts : 1))
+	OMPI_VERSION="$OPENMPI4_VERSION"
+	set_ompi_path # set OpenMPI PATH
 	for DIRAC_VERSION in $INSTALL_DIRAC_VERSIONS; do
 		if (("$DIRAC_NPROCS" <= 1)); then # Serial build
 			echo "DIRAC will be built in serial mode."
@@ -418,31 +418,6 @@ function setup_dirac() {
 	done
 	wait
 	cd "$SCRIPT_PATH"
-}
-
-function setup_python() {
-	echo "Start python setup..."
-	PYENVROOT="$INSTALL_PATH/.pyenv"
-	SKIP_PYENV_INSTALL="Y"
-	# if PYENVROOT exists, skip clone
-	if [ ! -d "$PYENVROOT" ]; then
-		git clone https://github.com/pyenv/pyenv.git "$PYENVROOT"
-		SKIP_PYENV_INSTALL="N"
-	fi
-	export PYENV_ROOT="$INSTALL_PATH/.pyenv"
-	export PATH="$PYENV_ROOT/bin:$PATH"
-	eval "$(pyenv init -)"
-	echo "$PYENV_ROOT , $INSTALL_PATH, skip? : $SKIP_PYENV_INSTALL" >"$SCRIPT_PATH/python-version.log" 2>&1
-	if [ "$SKIP_PYENV_INSTALL" = "N" ]; then
-		echo "export PYENV_ROOT=\"$PYENVROOT\"" >>"$HOME/.bashrc"
-		echo "command -v pyenv >/dev/null || export PATH=\"$PYENVROOT/bin:\$PATH\"" >>"$HOME/.bashrc"
-		echo 'eval "$(pyenv init -)"' >>"$HOME/.bashrc"
-		export MAKE_OPTS="-j${SETUP_NPROCS}"
-		pyenv install "$PYTHON2_VERSION"
-		pyenv install "$PYTHON3_VERSION"
-	fi
-	pyenv global "$PYTHON2_VERSION"
-	python -V >>"$SCRIPT_PATH/python-version.log" 2>&1
 }
 
 function setup_cmake() {
@@ -474,9 +449,11 @@ function build_openmpi() {
 	make -j "$OPENMPI_NPROCS" && make install && make check
 	mkdir -p "${MODULEFILES}/openmpi"
 	cp -f "${SCRIPT_PATH}/openmpi/${OMPI_VERSION}-intel" "${MODULEFILES}/openmpi"
-	echo "prepend-path	PATH			${OMPI_INSTALL_PREFIX}/bin" >>"${MODULEFILES}/openmpi/${OMPI_VERSION}-intel"
-	echo "prepend-path	LIBRARY_PATH	${OMPI_INSTALL_PREFIX}/lib" >>"${MODULEFILES}/openmpi/${OMPI_VERSION}-intel"
-	echo "prepend-path	LD_LIBRARY_PATH	${OMPI_INSTALL_PREFIX}/lib" >>"${MODULEFILES}/openmpi/${OMPI_VERSION}-intel"
+	{
+		echo "prepend-path	PATH			${OMPI_INSTALL_PREFIX}/bin"
+		echo "prepend-path	LIBRARY_PATH	${OMPI_INSTALL_PREFIX}/lib"
+		echo "prepend-path	LD_LIBRARY_PATH	${OMPI_INSTALL_PREFIX}/lib"
+	} >>"${MODULEFILES}/openmpi/${OMPI_VERSION}-intel"
 }
 
 function setup_openmpi() {
@@ -489,13 +466,19 @@ function setup_openmpi() {
 }
 
 function set_process_number() {
-	expr $SETUP_NPROCS / 2 >/dev/null 2>&1 || SETUP_NPROCS=1           # Is $SETUP_NPROCS a number? If not, set it to 1.
-	MAX_NPROCS=$(cpuinfo | grep "Processors(CPUs)" | awk '{print $3}') # Get the number of CPUs.
-	if (("$SETUP_NPROCS" < 0)); then                                   # invalid number of processes (negative numbers, etc.)
+	# Is $SETUP_NPROCS a number? If not, set it to 1.
+	if ! [[ "$SETUP_NPROCS" =~ ^[0-9]+$ ]]; then
 		echo "invalid number of processes: $SETUP_NPROCS"
 		echo "use default number of processes: 1"
 		SETUP_NPROCS=1
-	elif (("$SETUP_NPROCS > $MAX_NPROCS")); then # number of processes is larger than the number of processors
+	fi
+	MAX_NPROCS=$(cpuinfo | grep "Processors(CPUs)" | awk '{print $3}') # Get the number of CPUs.
+	if ! [[ "$MAX_NPROCS" =~ ^[0-9]+$ ]]; then
+		echo "invalid number of processors: $MAX_NPROCS"
+		echo "use default number of processors: 1"
+		MAX_NPROCS=1
+	fi
+	if (("$SETUP_NPROCS > $MAX_NPROCS")); then # number of processes is larger than the number of processors
 		echo "number of processors you want to use: $SETUP_NPROCS"
 		echo "number of processors you can use: $MAX_NPROCS"
 		echo "use max number of processes: $MAX_NPROCS"
@@ -677,7 +660,7 @@ function is_enviroment_modules_installed() {
 		echo "(e.g. module use --append ${MODULEFILES})"
 		module use --append "${MODULEFILES}"
 		echo "module use --append ${MODULEFILES}" >>"$HOME/.bashrc"
-		echo "Info: Add the modulefiles to your bashrc file. (module use --append ${MODULEFILES})"
+		echo "Info: Add the modulefiles to your .bashrc file. (module use --append ${MODULEFILES})"
 	else
 		echo "Enviroment Modules is not installed"
 		echo "After Enviroment Modules is installed, you can use module command (c.f. http://modules.sourceforge.net/)"
@@ -713,8 +696,6 @@ UTCHEM="${INSTALL_PATH}/utchem"
 # VERSIONS
 CMAKE_VERSION="3.23.2"
 OPENMPI4_VERSION="4.1.2"
-PYTHON2_VERSION="2.7.18"
-PYTHON3_VERSION="3.9.12"
 
 # Check whether the environment modules (http://modules.sourceforge.net/) is already installed
 is_enviroment_modules_installed
@@ -723,7 +704,7 @@ check_files_and_dirs
 
 # Install programs
 setup_cmake
-. "$SCRIPT_PATH/setup-pyenv" --parallel "$SETUP_NPROCS"
+source "$SCRIPT_PATH/setup-pyenv" --parallel "$SETUP_NPROCS"
 
 if [ "$INSTALL_UTCHEM" == "YES" ] || [ "$INSTALL_DIRAC" == "YES" ]; then
 	setup_openmpi
